# https://circleci.com/developer/orbs/orb/circleci/node
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  phdcc_papers_coverage:
    jobs:
      - test_coverage
jobs:
  test_coverage:
    executor: node/default
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          lts: true
      - run: npm -v
      - run: node -v
      - run: npm install
      - run: npm install coveralls

      # Install Cypress dependencies
      - run: sudo apt-get update --fix-missing
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      ################
      # START API SERVER
      - run: cd ..;git clone https://github.com/phdccltd/phdcc-papers-api.git
      - run: mkdir ../phdcc-papers-api/testfilesdir
      - run: mkdir ../phdcc-papers-api/testtmpdir
      - run: cd ../phdcc-papers-api; npm install
      - run:
          name: run API server
          command: cd ../phdcc-papers-api; npm run forclient
          background: true

      - run: npm run waitonapi
      
      ################
      # MAKE clienttest ENVIRONMENT VARIABLES FILE
      - run: echo "CYPRESS_COVERAGE='true'" >.env.clienttest
      - run: echo "NUXT_PORT=3000" >>.env.clienttest
      - run: echo "NUXT_PUBLIC_SITE='https://example.org'" >>.env.clienttest
      - run: echo "NUXT_PUBLIC_API='http://localhost:9000/api'" >>.env.clienttest
      - run: echo "RECAPTCHA_BYPASS='avoidrecaptcha'" >>.env.clienttest

      ################
      # RUN CLIENT SERVER
      - run:
          name: run client server
          command: npm run clienttest
          background: true

      - run: npm run waitonclient

      ################
      # RUN CYPRESS TESTS
      - run: mkdir .nyc_output
      - run: mkdir coverage
      - run: npm run cypress

      ################
      # Upload results to coveralls
      # 24/6/23 after various updates, coverage/lcov.info not generated
      - run: ls -l .nyc_output
      - run: ls -l coverage
      #- run: node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info # .coveralls.yml must contain circleci and add environment variable COVERALLS_REPO_TOKEN
